package nurapi;

import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;

/**
 * Contains the custom hoptable configuration, extended version: + LBT + max TX level.
 * <br>
 *
 * @sa NurApiGetCustomHoptableEx()<br>
 * <i>native declaration : nur_sdk-master\native\include\NurAPI.h:376</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("NurApi")
public class NUR_CUSTOMHOP_PARAMS_EX extends StructObject {
    static {
        BridJ.register();
    }

    public NUR_CUSTOMHOP_PARAMS_EX() {
        super();
    }

    public NUR_CUSTOMHOP_PARAMS_EX(Pointer pointer) {
        super(pointer);
    }

    /**
     * < Number of channels in this table.
     */
    @Field(0)
    public int count() {
        return this.io.getIntField(this, 0);
    }

    /**
     * < Number of channels in this table.
     */
    @Field(0)
    public NUR_CUSTOMHOP_PARAMS_EX count(int count) {
        this.io.setIntField(this, 0, count);
        return this;
    }

    /**
     * < Channel time in milliseconds.
     */
    @Field(1)
    public int chTime() {
        return this.io.getIntField(this, 1);
    }

    /**
     * < Channel time in milliseconds.
     */
    @Field(1)
    public NUR_CUSTOMHOP_PARAMS_EX chTime(int chTime) {
        this.io.setIntField(this, 1, chTime);
        return this;
    }

    /**
     * < Silent time in milliseconds, if any, between channel change.
     */
    @Field(2)
    public int silentTime() {
        return this.io.getIntField(this, 2);
    }

    /**
     * < Silent time in milliseconds, if any, between channel change.
     */
    @Field(2)
    public NUR_CUSTOMHOP_PARAMS_EX silentTime(int silentTime) {
        this.io.setIntField(this, 2, silentTime);
        return this;
    }

    /**
     * < Maximum link frequency.
     */
    @Field(3)
    public int maxBLF() {
        return this.io.getIntField(this, 3);
    }

    /**
     * < Maximum link frequency.
     */
    @Field(3)
    public NUR_CUSTOMHOP_PARAMS_EX maxBLF(int maxBLF) {
        this.io.setIntField(this, 3, maxBLF);
        return this;
    }

    /**
     * < Tari: 1=12.5 and 2 = 25.
     */
    @Field(4)
    public int Tari() {
        return this.io.getIntField(this, 4);
    }

    /**
     * < Tari: 1=12.5 and 2 = 25.
     */
    @Field(4)
    public NUR_CUSTOMHOP_PARAMS_EX Tari(int Tari) {
        this.io.setIntField(this, 4, Tari);
        return this;
    }

    /**
     * < LBT threshold; minimum value is -90.
     */
    @Field(5)
    public int lbtThresh() {
        return this.io.getIntField(this, 5);
    }

    /**
     * < LBT threshold; minimum value is -90.
     */
    @Field(5)
    public NUR_CUSTOMHOP_PARAMS_EX lbtThresh(int lbtThresh) {
        this.io.setIntField(this, 5, lbtThresh);
        return this;
    }

    /**
     * < Maximum TX level; range is 0...19.
     */
    @Field(6)
    public int maxTxLevel() {
        return this.io.getIntField(this, 6);
    }

    /**
     * < Maximum TX level; range is 0...19.
     */
    @Field(6)
    public NUR_CUSTOMHOP_PARAMS_EX maxTxLevel(int maxTxLevel) {
        this.io.setIntField(this, 6, maxTxLevel);
        return this;
    }

    /**
     * < Frequencies in kHz. Number of populated antries is stated with the 'count'.<br>
     * C type : DWORD[100]
     */
    @Array({100})
    @Field(7)
    public Pointer<Integer> freqs() {
        return this.io.getPointerField(this, 7);
    }
}
