package nurapi;

import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;

/**
 * Contains Ethernet Sampo device information.
 * <br>
 *
 * @sa NUR_NOTIFICATION_DEVSEARCH<br>
 * <i>native declaration : nur_sdk-master\native\include\NurAPI.h:458</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("NurApi")
public class NUR_NETDEV_INFO extends StructObject {
    static {
        BridJ.register();
    }

    public NUR_NETDEV_INFO() {
        super();
    }

    public NUR_NETDEV_INFO(Pointer pointer) {
        super(pointer);
    }

    @Field(0)
    public byte status() {
        return this.io.getByteField(this, 0);
    }

    @Field(0)
    public NUR_NETDEV_INFO status(byte status) {
        this.io.setByteField(this, 0, status);
        return this;
    }

    @Field(1)
    public byte boardID() {
        return this.io.getByteField(this, 1);
    }

    @Field(1)
    public NUR_NETDEV_INFO boardID(byte boardID) {
        this.io.setByteField(this, 1, boardID);
        return this;
    }

    @Field(2)
    public byte boardType() {
        return this.io.getByteField(this, 2);
    }

    @Field(2)
    public NUR_NETDEV_INFO boardType(byte boardType) {
        this.io.setByteField(this, 2, boardType);
        return this;
    }

    @Field(3)
    public double temp() {
        return this.io.getDoubleField(this, 3);
    }

    @Field(3)
    public NUR_NETDEV_INFO temp(double temp) {
        this.io.setDoubleField(this, 3, temp);
        return this;
    }

    @Field(4)
    public int lightADC() {
        return this.io.getIntField(this, 4);
    }

    @Field(4)
    public NUR_NETDEV_INFO lightADC(int lightADC) {
        this.io.setIntField(this, 4, lightADC);
        return this;
    }

    @Field(5)
    public int tapADC() {
        return this.io.getIntField(this, 5);
    }

    @Field(5)
    public NUR_NETDEV_INFO tapADC(int tapADC) {
        this.io.setIntField(this, 5, tapADC);
        return this;
    }

    @Field(6)
    public byte IOstate() {
        return this.io.getByteField(this, 6);
    }

    @Field(6)
    public NUR_NETDEV_INFO IOstate(byte IOstate) {
        this.io.setByteField(this, 6, IOstate);
        return this;
    }

    @Field(7)
    public int upTime() {
        return this.io.getIntField(this, 7);
    }

    @Field(7)
    public NUR_NETDEV_INFO upTime(int upTime) {
        this.io.setIntField(this, 7, upTime);
        return this;
    }

    /**
     * C type : BYTE[3]
     */
    @Array({3})
    @Field(8)
    public Pointer<Byte> nurVer() {
        return this.io.getPointerField(this, 8);
    }

    /**
     * C type : char[16]
     */
    @Array({16})
    @Field(9)
    public Pointer<Byte> serial() {
        return this.io.getPointerField(this, 9);
    }

    /**
     * C type : char[16]
     */
    @Array({16})
    @Field(10)
    public Pointer<Byte> altSerial() {
        return this.io.getPointerField(this, 10);
    }

    /**
     * C type : char[16]
     */
    @Array({16})
    @Field(11)
    public Pointer<Byte> nurName() {
        return this.io.getPointerField(this, 11);
    }

    /**
     * C type : char[8]
     */
    @Array({8})
    @Field(12)
    public Pointer<Byte> hwVer() {
        return this.io.getPointerField(this, 12);
    }

    @Field(13)
    public byte nurAntNum() {
        return this.io.getByteField(this, 13);
    }

    @Field(13)
    public NUR_NETDEV_INFO nurAntNum(byte nurAntNum) {
        this.io.setByteField(this, 13, nurAntNum);
        return this;
    }

    /**
     * C type : NUR_ETHDEV_CONFIG
     */
    @Field(14)
    public NUR_ETHDEV_CONFIG eth() {
        return this.io.getNativeObjectField(this, 14);
    }

    /**
     * C type : NUR_ETHDEV_CONFIG
     */
    @Field(14)
    public NUR_NETDEV_INFO eth(NUR_ETHDEV_CONFIG eth) {
        this.io.setNativeObjectField(this, 14, eth);
        return this;
    }
}
