package nurapi;

import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;

/**
 * Data sent with notification NUR_NOTIFICATION_INVENTORYSTREAM.
 * <br>
 * Use NurApiGetTagCount(), NurApiGetTagData(), NurApiClearTags() functions to access tag data.
 * <br>
 *
 * <br>
 *
 * @sa NUR_NOTIFICATION_INVENTORYSTREAM, enum NUR_NOTIFICATION<br>
 * <i>native declaration : nur_sdk-master\native\include\NurAPI.h:122</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("NurApi")
public class NUR_INVENTORYSTREAM_DATA extends StructObject {
    static {
        BridJ.register();
    }

    public NUR_INVENTORYSTREAM_DATA() {
        super();
    }

    public NUR_INVENTORYSTREAM_DATA(Pointer pointer) {
        super(pointer);
    }

    /**
     * < Number of tags added to NurApi internal tag storage.
     */
    @Field(0)
    public int tagsAdded() {
        return this.io.getIntField(this, 0);
    }

    /**
     * < Number of tags added to NurApi internal tag storage.
     */
    @Field(0)
    public NUR_INVENTORYSTREAM_DATA tagsAdded(int tagsAdded) {
        this.io.setIntField(this, 0, tagsAdded);
        return this;
    }

    /**
     * < Streaming has stopped. If you need continuous streaming, you need to restart streaming.
     */
    @Field(1)
    public int stopped() {
        return this.io.getIntField(this, 1);
    }

    /**
     * < Streaming has stopped. If you need continuous streaming, you need to restart streaming.
     */
    @Field(1)
    public NUR_INVENTORYSTREAM_DATA stopped(int stopped) {
        this.io.setIntField(this, 1, stopped);
        return this;
    }

    /**
     * < Number of full Q rounds done in this inventory.
     */
    @Field(2)
    public int roundsDone() {
        return this.io.getIntField(this, 2);
    }

    /**
     * < Number of full Q rounds done in this inventory.
     */
    @Field(2)
    public NUR_INVENTORYSTREAM_DATA roundsDone(int roundsDone) {
        this.io.setIntField(this, 2, roundsDone);
        return this;
    }

    /**
     * < Number of possible collisions or reception errors in this inventory.
     */
    @Field(3)
    public int collisions() {
        return this.io.getIntField(this, 3);
    }

    /**
     * < Number of possible collisions or reception errors in this inventory.
     */
    @Field(3)
    public NUR_INVENTORYSTREAM_DATA collisions(int collisions) {
        this.io.setIntField(this, 3, collisions);
        return this;
    }

    /**
     * < Q used in this inventory.
     */
    @Field(4)
    public int Q() {
        return this.io.getIntField(this, 4);
    }

    /**
     * < Q used in this inventory.
     */
    @Field(4)
    public NUR_INVENTORYSTREAM_DATA Q(int Q) {
        this.io.setIntField(this, 4, Q);
        return this;
    }
}
