package nurapi;

import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;

/**
 * Tag tracking tag<br>
 * <i>native declaration : nur_sdk-master\native\include\NurAPI.h:43</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("NurApi")
public class NUR_TT_TAG extends StructObject {
    static {
        BridJ.register();
    }

    public NUR_TT_TAG() {
        super();
    }

    public NUR_TT_TAG(Pointer pointer) {
        super(pointer);
    }

    /**
     * C type : BYTE[(64)]
     */
    @Array({64})
    @Field(0)
    public Pointer<Byte> epc() {
        return this.io.getPointerField(this, 0);
    }

    @Field(1)
    public byte epcLen() {
        return this.io.getByteField(this, 1);
    }

    @Field(1)
    public NUR_TT_TAG epcLen(byte epcLen) {
        this.io.setByteField(this, 1, epcLen);
        return this;
    }

    @Field(2)
    public int changedEvents() {
        return this.io.getIntField(this, 2);
    }

    @Field(2)
    public NUR_TT_TAG changedEvents(int changedEvents) {
        this.io.setIntField(this, 2, changedEvents);
        return this;
    }

    @Field(3)
    public long lastUpdateTime() {
        return this.io.getLongField(this, 3);
    }

    @Field(3)
    public NUR_TT_TAG lastUpdateTime(long lastUpdateTime) {
        this.io.setLongField(this, 3, lastUpdateTime);
        return this;
    }

    @Field(4)
    public long lastSeenTime() {
        return this.io.getLongField(this, 4);
    }

    @Field(4)
    public NUR_TT_TAG lastSeenTime(long lastSeenTime) {
        this.io.setLongField(this, 4, lastSeenTime);
        return this;
    }

    /**
     * C type : signed char[NUR_MAX_ANTENNAS_EX]
     */
    @Array({32})
    @Field(5)
    public Pointer<Byte> rssi() {
        return this.io.getPointerField(this, 5);
    }

    @Field(6)
    public int maxScaledRssi() {
        return this.io.getIntField(this, 6);
    }

    @Field(6)
    public NUR_TT_TAG maxScaledRssi(int maxScaledRssi) {
        this.io.setIntField(this, 6, maxScaledRssi);
        return this;
    }

    @Field(7)
    public int maxRssi() {
        return this.io.getIntField(this, 7);
    }

    @Field(7)
    public NUR_TT_TAG maxRssi(int maxRssi) {
        this.io.setIntField(this, 7, maxRssi);
        return this;
    }

    @Field(8)
    public int maxRssiAnt() {
        return this.io.getIntField(this, 8);
    }

    @Field(8)
    public NUR_TT_TAG maxRssiAnt(int maxRssiAnt) {
        this.io.setIntField(this, 8, maxRssiAnt);
        return this;
    }

    @Field(9)
    public byte visible() {
        return this.io.getByteField(this, 9);
    }

    @Field(9)
    public NUR_TT_TAG visible(byte visible) {
        this.io.setByteField(this, 9, visible);
        return this;
    }

    @Field(10)
    public float X() {
        return this.io.getFloatField(this, 10);
    }

    @Field(10)
    public NUR_TT_TAG X(float X) {
        this.io.setFloatField(this, 10, X);
        return this;
    }

    @Field(11)
    public float Y() {
        return this.io.getFloatField(this, 11);
    }

    @Field(11)
    public NUR_TT_TAG Y(float Y) {
        this.io.setFloatField(this, 11, Y);
        return this;
    }

    @Field(12)
    public int prevSector() {
        return this.io.getIntField(this, 12);
    }

    @Field(12)
    public NUR_TT_TAG prevSector(int prevSector) {
        this.io.setIntField(this, 12, prevSector);
        return this;
    }

    @Field(13)
    public int sector() {
        return this.io.getIntField(this, 13);
    }

    @Field(13)
    public NUR_TT_TAG sector(int sector) {
        this.io.setIntField(this, 13, sector);
        return this;
    }

    @Field(14)
    public int firstTTIOReadSource() {
        return this.io.getIntField(this, 14);
    }

    @Field(14)
    public NUR_TT_TAG firstTTIOReadSource(int firstTTIOReadSource) {
        this.io.setIntField(this, 14, firstTTIOReadSource);
        return this;
    }

    @Field(15)
    public int secondTTIOReadSource() {
        return this.io.getIntField(this, 15);
    }

    @Field(15)
    public NUR_TT_TAG secondTTIOReadSource(int secondTTIOReadSource) {
        this.io.setIntField(this, 15, secondTTIOReadSource);
        return this;
    }

    @Field(16)
    public int directionTTIO() {
        return this.io.getIntField(this, 16);
    }

    @Field(16)
    public NUR_TT_TAG directionTTIO(int directionTTIO) {
        this.io.setIntField(this, 16, directionTTIO);
        return this;
    }

    /**
     * C type : int[NUR_MAX_ANTENNAS_EX]
     */
    @Array({32})
    @Field(17)
    public Pointer<Integer> scaledRssi() {
        return this.io.getPointerField(this, 17);
    }

    /**
     * C type : DWORD[NUR_MAX_ANTENNAS_EX]
     */
    @Array({32})
    @Field(18)
    public Pointer<Integer> seenCnt() {
        return this.io.getPointerField(this, 18);
    }
}
