package nurapi;

import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;

/**
 * Nur module setup structure.
 * <br>
 *
 * @sa NurApiGetModuleSetup(), NurApiSetModuleSetup(), NUR_MODULESETUP_FLAGS, NurApiStoreCurrentSetup(), NurApiStoreCurrentSetupEx()<br>
 * <i>native declaration : nur_sdk-master\native\include\NurAPI.h:316</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("NurApi")
public class NUR_MODULESETUP extends StructObject {
    static {
        BridJ.register();
    }

    public NUR_MODULESETUP() {
        super();
    }

    public NUR_MODULESETUP(Pointer pointer) {
        super(pointer);
    }

    @Field(0)
    public int linkFreq() {
        return this.io.getIntField(this, 0);
    }

    @Field(0)
    public NUR_MODULESETUP linkFreq(int linkFreq) {
        this.io.setIntField(this, 0, linkFreq);
        return this;
    }

    @Field(1)
    public int rxDecoding() {
        return this.io.getIntField(this, 1);
    }

    @Field(1)
    public NUR_MODULESETUP rxDecoding(int rxDecoding) {
        this.io.setIntField(this, 1, rxDecoding);
        return this;
    }

    @Field(2)
    public int txLevel() {
        return this.io.getIntField(this, 2);
    }

    @Field(2)
    public NUR_MODULESETUP txLevel(int txLevel) {
        this.io.setIntField(this, 2, txLevel);
        return this;
    }

    @Field(3)
    public int txModulation() {
        return this.io.getIntField(this, 3);
    }

    @Field(3)
    public NUR_MODULESETUP txModulation(int txModulation) {
        this.io.setIntField(this, 3, txModulation);
        return this;
    }

    @Field(4)
    public int regionId() {
        return this.io.getIntField(this, 4);
    }

    @Field(4)
    public NUR_MODULESETUP regionId(int regionId) {
        this.io.setIntField(this, 4, regionId);
        return this;
    }

    @Field(5)
    public int inventoryQ() {
        return this.io.getIntField(this, 5);
    }

    @Field(5)
    public NUR_MODULESETUP inventoryQ(int inventoryQ) {
        this.io.setIntField(this, 5, inventoryQ);
        return this;
    }

    @Field(6)
    public int inventorySession() {
        return this.io.getIntField(this, 6);
    }

    @Field(6)
    public NUR_MODULESETUP inventorySession(int inventorySession) {
        this.io.setIntField(this, 6, inventorySession);
        return this;
    }

    @Field(7)
    public int inventoryRounds() {
        return this.io.getIntField(this, 7);
    }

    @Field(7)
    public NUR_MODULESETUP inventoryRounds(int inventoryRounds) {
        this.io.setIntField(this, 7, inventoryRounds);
        return this;
    }

    @Field(8)
    public int antennaMask() {
        return this.io.getIntField(this, 8);
    }

    @Field(8)
    public NUR_MODULESETUP antennaMask(int antennaMask) {
        this.io.setIntField(this, 8, antennaMask);
        return this;
    }

    @Field(9)
    public int scanSingleTriggerTimeout() {
        return this.io.getIntField(this, 9);
    }

    @Field(9)
    public NUR_MODULESETUP scanSingleTriggerTimeout(int scanSingleTriggerTimeout) {
        this.io.setIntField(this, 9, scanSingleTriggerTimeout);
        return this;
    }

    @Field(10)
    public int inventoryTriggerTimeout() {
        return this.io.getIntField(this, 10);
    }

    @Field(10)
    public NUR_MODULESETUP inventoryTriggerTimeout(int inventoryTriggerTimeout) {
        this.io.setIntField(this, 10, inventoryTriggerTimeout);
        return this;
    }

    @Field(11)
    public int selectedAntenna() {
        return this.io.getIntField(this, 11);
    }

    @Field(11)
    public NUR_MODULESETUP selectedAntenna(int selectedAntenna) {
        this.io.setIntField(this, 11, selectedAntenna);
        return this;
    }

    @Field(12)
    public int opFlags() {
        return this.io.getIntField(this, 12);
    }

    @Field(12)
    public NUR_MODULESETUP opFlags(int opFlags) {
        this.io.setIntField(this, 12, opFlags);
        return this;
    }

    @Field(13)
    public int inventoryTarget() {
        return this.io.getIntField(this, 13);
    }

    @Field(13)
    public NUR_MODULESETUP inventoryTarget(int inventoryTarget) {
        this.io.setIntField(this, 13, inventoryTarget);
        return this;
    }

    @Field(14)
    public int inventoryEpcLength() {
        return this.io.getIntField(this, 14);
    }

    @Field(14)
    public NUR_MODULESETUP inventoryEpcLength(int inventoryEpcLength) {
        this.io.setIntField(this, 14, inventoryEpcLength);
        return this;
    }

    /**
     * C type : NUR_RSSI_FILTER
     */
    @Field(15)
    public NUR_RSSI_FILTER readRssiFilter() {
        return this.io.getNativeObjectField(this, 15);
    }

    /**
     * C type : NUR_RSSI_FILTER
     */
    @Field(15)
    public NUR_MODULESETUP readRssiFilter(NUR_RSSI_FILTER readRssiFilter) {
        this.io.setNativeObjectField(this, 15, readRssiFilter);
        return this;
    }

    /**
     * C type : NUR_RSSI_FILTER
     */
    @Field(16)
    public NUR_RSSI_FILTER writeRssiFilter() {
        return this.io.getNativeObjectField(this, 16);
    }

    /**
     * C type : NUR_RSSI_FILTER
     */
    @Field(16)
    public NUR_MODULESETUP writeRssiFilter(NUR_RSSI_FILTER writeRssiFilter) {
        this.io.setNativeObjectField(this, 16, writeRssiFilter);
        return this;
    }

    /**
     * C type : NUR_RSSI_FILTER
     */
    @Field(17)
    public NUR_RSSI_FILTER inventoryRssiFilter() {
        return this.io.getNativeObjectField(this, 17);
    }

    /**
     * C type : NUR_RSSI_FILTER
     */
    @Field(17)
    public NUR_MODULESETUP inventoryRssiFilter(NUR_RSSI_FILTER inventoryRssiFilter) {
        this.io.setNativeObjectField(this, 17, inventoryRssiFilter);
        return this;
    }

    @Field(18)
    public int readTO() {
        return this.io.getIntField(this, 18);
    }

    @Field(18)
    public NUR_MODULESETUP readTO(int readTO) {
        this.io.setIntField(this, 18, readTO);
        return this;
    }

    @Field(19)
    public int writeTO() {
        return this.io.getIntField(this, 19);
    }

    @Field(19)
    public NUR_MODULESETUP writeTO(int writeTO) {
        this.io.setIntField(this, 19, writeTO);
        return this;
    }

    @Field(20)
    public int lockTO() {
        return this.io.getIntField(this, 20);
    }

    @Field(20)
    public NUR_MODULESETUP lockTO(int lockTO) {
        this.io.setIntField(this, 20, lockTO);
        return this;
    }

    @Field(21)
    public int killTO() {
        return this.io.getIntField(this, 21);
    }

    @Field(21)
    public NUR_MODULESETUP killTO(int killTO) {
        this.io.setIntField(this, 21, killTO);
        return this;
    }

    @Field(22)
    public int periodSetup() {
        return this.io.getIntField(this, 22);
    }

    @Field(22)
    public NUR_MODULESETUP periodSetup(int periodSetup) {
        this.io.setIntField(this, 22, periodSetup);
        return this;
    }

    /**
     * C type : int[NUR_MAX_ANTENNAS]
     */
    @Array({4})
    @Field(23)
    public Pointer<Integer> antPower() {
        return this.io.getPointerField(this, 23);
    }

    /**
     * C type : int[NUR_MAX_ANTENNAS]
     */
    @Array({4})
    @Field(24)
    public Pointer<Integer> powerOffset() {
        return this.io.getPointerField(this, 24);
    }

    @Field(25)
    public int antennaMaskEx() {
        return this.io.getIntField(this, 25);
    }

    @Field(25)
    public NUR_MODULESETUP antennaMaskEx(int antennaMaskEx) {
        this.io.setIntField(this, 25, antennaMaskEx);
        return this;
    }

    /**
     * C type : NUR_AUTOTUNE_SETUP
     */
    @Field(26)
    public NUR_AUTOTUNE_SETUP autotune() {
        return this.io.getNativeObjectField(this, 26);
    }

    /**
     * C type : NUR_AUTOTUNE_SETUP
     */
    @Field(26)
    public NUR_MODULESETUP autotune(NUR_AUTOTUNE_SETUP autotune) {
        this.io.setNativeObjectField(this, 26, autotune);
        return this;
    }

    /**
     * C type : int[NUR_MAX_ANTENNAS_EX]
     */
    @Array({32})
    @Field(27)
    public Pointer<Integer> antPowerEx() {
        return this.io.getPointerField(this, 27);
    }

    @Field(28)
    public int rxSensitivity() {
        return this.io.getIntField(this, 28);
    }

    @Field(28)
    public NUR_MODULESETUP rxSensitivity(int rxSensitivity) {
        this.io.setIntField(this, 28, rxSensitivity);
        return this;
    }

    @Field(29)
    public int rfProfile() {
        return this.io.getIntField(this, 29);
    }

    @Field(29)
    public NUR_MODULESETUP rfProfile(int rfProfile) {
        this.io.setIntField(this, 29, rfProfile);
        return this;
    }
}
