package nurapi;

import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;

/**
 * Data sent within scan start/stop event.<br>
 * <i>native declaration : nur_sdk-master\native\include\NurAPI.h:55</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("NurApi")
public class NUR_TTSCAN_DATA extends StructObject {
    static {
        BridJ.register();
    }

    public NUR_TTSCAN_DATA() {
        super();
    }

    public NUR_TTSCAN_DATA(Pointer pointer) {
        super(pointer);
    }

    @Field(0)
    public int readSource() {
        return this.io.getIntField(this, 0);
    }

    @Field(0)
    public NUR_TTSCAN_DATA readSource(int readSource) {
        this.io.setIntField(this, 0, readSource);
        return this;
    }

    @Field(1)
    public int started() {
        return this.io.getIntField(this, 1);
    }

    @Field(1)
    public NUR_TTSCAN_DATA started(int started) {
        this.io.setIntField(this, 1, started);
        return this;
    }
}
