package nurapi;

import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;

/**
 * Notification about the last programmed EPC during the EPC enumeration based on TID contents.<br>
 * <i>native declaration : nur_sdk-master\native\include\NurAPI.h:141</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("NurApi")
public class NUR_EPCENUMSTREAM_DATA extends StructObject {
    static {
        BridJ.register();
    }

    public NUR_EPCENUMSTREAM_DATA() {
        super();
    }

    public NUR_EPCENUMSTREAM_DATA(Pointer pointer) {
        super(pointer);
    }

    /**
     * < Length of the EPC data. This is the last programmed EPC.
     */
    @Field(0)
    public int epcLen() {
        return this.io.getIntField(this, 0);
    }

    /**
     * < Length of the EPC data. This is the last programmed EPC.
     */
    @Field(0)
    public NUR_EPCENUMSTREAM_DATA epcLen(int epcLen) {
        this.io.setIntField(this, 0, epcLen);
        return this;
    }

    /**
     * < Content of the last programmed EPC.<br>
     * C type : BYTE[16]
     */
    @Array({16})
    @Field(1)
    public Pointer<Byte> lastEPC() {
        return this.io.getPointerField(this, 1);
    }

    /**
     * < This is the word address where the TID data was read from.
     */
    @Field(2)
    public int tidwAddr() {
        return this.io.getIntField(this, 2);
    }

    /**
     * < This is the word address where the TID data was read from.
     */
    @Field(2)
    public NUR_EPCENUMSTREAM_DATA tidwAddr(int tidwAddr) {
        this.io.setIntField(this, 2, tidwAddr);
        return this;
    }

    /**
     * < Length of the TID data. This is the TID data with which the EPC was assigned by.
     */
    @Field(3)
    public int tidLen() {
        return this.io.getIntField(this, 3);
    }

    /**
     * < Length of the TID data. This is the TID data with which the EPC was assigned by.
     */
    @Field(3)
    public NUR_EPCENUMSTREAM_DATA tidLen(int tidLen) {
        this.io.setIntField(this, 3, tidLen);
        return this;
    }

    /**
     * < Content of the TID data.<br>
     * C type : BYTE[16]
     */
    @Array({16})
    @Field(4)
    public Pointer<Byte> tidData() {
        return this.io.getPointerField(this, 4);
    }
}
