package nurapi;

import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;

/**
 * Data sent with notification NUR_NOTIFICATION_EASALARM.
 * <br>
 * <br>
 *
 * @note Not supported in firmware version 3.1-A or older.
 * <br>
 * <br>
 * @sa NUR_NOTIFICATION_EASALARM, enum NUR_NOTIFICATION, NurApiNXPStartAlarmStream(), NurApiNXPStopAlarmStream(), NurApiIsNXPAlarmStreamRunning()<br>
 * <i>native declaration : nur_sdk-master\native\include\NurAPI.h:133</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("NurApi")
public class NUR_EASALARMSTREAM_DATA extends StructObject {
    static {
        BridJ.register();
    }

    public NUR_EASALARMSTREAM_DATA() {
        super();
    }

    public NUR_EASALARMSTREAM_DATA(Pointer pointer) {
        super(pointer);
    }

    /**
     * < Streaming has stopped. If you need continuous streaming, you need to restart streaming.
     */
    @Field(0)
    public int stopped() {
        return this.io.getIntField(this, 0);
    }

    /**
     * < Streaming has stopped. If you need continuous streaming, you need to restart streaming.
     */
    @Field(0)
    public NUR_EASALARMSTREAM_DATA stopped(int stopped) {
        this.io.setIntField(this, 0, stopped);
        return this;
    }

    /**
     * < If TRUE, EAS Alarm is active.
     */
    @Field(1)
    public int armed() {
        return this.io.getIntField(this, 1);
    }

    /**
     * < If TRUE, EAS Alarm is active.
     */
    @Field(1)
    public NUR_EASALARMSTREAM_DATA armed(int armed) {
        this.io.setIntField(this, 1, armed);
        return this;
    }
}
