package nurapi;

import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;

/**
 * NUR_NOTIFICATION_HOPEVENT data.<br>
 * <i>native declaration : nur_sdk-master\native\include\NurAPI.h:598</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("NurApi")
public class NUR_HOPEVENT_DATA extends StructObject {
    static {
        BridJ.register();
    }

    public NUR_HOPEVENT_DATA() {
        super();
    }

    public NUR_HOPEVENT_DATA(Pointer pointer) {
        super(pointer);
    }

    /**
     * < Current hop table region id
     */
    @Field(0)
    public byte hopTableId() {
        return this.io.getByteField(this, 0);
    }

    /**
     * < Current hop table region id
     */
    @Field(0)
    public NUR_HOPEVENT_DATA hopTableId(byte hopTableId) {
        this.io.setByteField(this, 0, hopTableId);
        return this;
    }

    /**
     * < Index of frequency in hop table
     */
    @Field(1)
    public byte freqIdx() {
        return this.io.getByteField(this, 1);
    }

    /**
     * < Index of frequency in hop table
     */
    @Field(1)
    public NUR_HOPEVENT_DATA freqIdx(byte freqIdx) {
        this.io.setByteField(this, 1, freqIdx);
        return this;
    }

    /**
     * < Frequency in kHz
     */
    @Field(2)
    public int freqKhz() {
        return this.io.getIntField(this, 2);
    }

    /**
     * < Frequency in kHz
     */
    @Field(2)
    public NUR_HOPEVENT_DATA freqKhz(int freqKhz) {
        this.io.setIntField(this, 2, freqKhz);
        return this;
    }
}
