package nurapi;

import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;

/**
 * Diagnostics report data.
 * <br>
 *
 * @sa NurApiDiagGetReport
 * <br>
 * @sa NurApiDiagGetConfig
 * <br>
 * @sa NurApiDiagSetConfig<br>
 * <i>native declaration : nur_sdk-master\native\include\NurAPI.h:692</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("NurApi")
public class NUR_DIAG_REPORT extends StructObject {
    static {
        BridJ.register();
    }

    public NUR_DIAG_REPORT() {
        super();
    }

    public NUR_DIAG_REPORT(Pointer pointer) {
        super(pointer);
    }

    /**
     * < Report flags. see enum NUR_DIAG_REPORT_FLAGS
     */
    @Field(0)
    public int flags() {
        return this.io.getIntField(this, 0);
    }

    /**
     * < Report flags. see enum NUR_DIAG_REPORT_FLAGS
     */
    @Field(0)
    public NUR_DIAG_REPORT flags(int flags) {
        this.io.setIntField(this, 0, flags);
        return this;
    }

    /**
     * < Uptime in milliseconds
     */
    @Field(1)
    public int uptime() {
        return this.io.getIntField(this, 1);
    }

    /**
     * < Uptime in milliseconds
     */
    @Field(1)
    public NUR_DIAG_REPORT uptime(int uptime) {
        this.io.setIntField(this, 1, uptime);
        return this;
    }

    /**
     * < RF on time in milliseconds
     */
    @Field(2)
    public int rfActiveTime() {
        return this.io.getIntField(this, 2);
    }

    /**
     * < RF on time in milliseconds
     */
    @Field(2)
    public NUR_DIAG_REPORT rfActiveTime(int rfActiveTime) {
        this.io.setIntField(this, 2, rfActiveTime);
        return this;
    }

    /**
     * < Temperature in celcius. 1000 if not supported
     */
    @Field(3)
    public int temperature() {
        return this.io.getIntField(this, 3);
    }

    /**
     * < Temperature in celcius. 1000 if not supported
     */
    @Field(3)
    public NUR_DIAG_REPORT temperature(int temperature) {
        this.io.setIntField(this, 3, temperature);
        return this;
    }

    /**
     * < Number of bytes in to module
     */
    @Field(4)
    public int bytesIn() {
        return this.io.getIntField(this, 4);
    }

    /**
     * < Number of bytes in to module
     */
    @Field(4)
    public NUR_DIAG_REPORT bytesIn(int bytesIn) {
        this.io.setIntField(this, 4, bytesIn);
        return this;
    }

    /**
     * < Number of bytes out from module
     */
    @Field(5)
    public int bytesOut() {
        return this.io.getIntField(this, 5);
    }

    /**
     * < Number of bytes out from module
     */
    @Field(5)
    public NUR_DIAG_REPORT bytesOut(int bytesOut) {
        this.io.setIntField(this, 5, bytesOut);
        return this;
    }

    /**
     * < Number of ignored (invalid) bytes
     */
    @Field(6)
    public int bytesIgnored() {
        return this.io.getIntField(this, 6);
    }

    /**
     * < Number of ignored (invalid) bytes
     */
    @Field(6)
    public NUR_DIAG_REPORT bytesIgnored(int bytesIgnored) {
        this.io.setIntField(this, 6, bytesIgnored);
        return this;
    }

    /**
     * < Number of bad antenna errors
     */
    @Field(7)
    public int antennaErrors() {
        return this.io.getIntField(this, 7);
    }

    /**
     * < Number of bad antenna errors
     */
    @Field(7)
    public NUR_DIAG_REPORT antennaErrors(int antennaErrors) {
        this.io.setIntField(this, 7, antennaErrors);
        return this;
    }

    /**
     * < Number of automatically recovered internal HW failures
     */
    @Field(8)
    public int hwErrors() {
        return this.io.getIntField(this, 8);
    }

    /**
     * < Number of automatically recovered internal HW failures
     */
    @Field(8)
    public NUR_DIAG_REPORT hwErrors(int hwErrors) {
        this.io.setIntField(this, 8, hwErrors);
        return this;
    }

    /**
     * < Number of successfully inventoried tags
     */
    @Field(9)
    public int invTags() {
        return this.io.getIntField(this, 9);
    }

    /**
     * < Number of successfully inventoried tags
     */
    @Field(9)
    public NUR_DIAG_REPORT invTags(int invTags) {
        this.io.setIntField(this, 9, invTags);
        return this;
    }

    /**
     * < Number of collisions during inventory
     */
    @Field(10)
    public int invColl() {
        return this.io.getIntField(this, 10);
    }

    /**
     * < Number of collisions during inventory
     */
    @Field(10)
    public NUR_DIAG_REPORT invColl(int invColl) {
        this.io.setIntField(this, 10, invColl);
        return this;
    }

    /**
     * < Number of successfully read tag commands
     */
    @Field(11)
    public int readTags() {
        return this.io.getIntField(this, 11);
    }

    /**
     * < Number of successfully read tag commands
     */
    @Field(11)
    public NUR_DIAG_REPORT readTags(int readTags) {
        this.io.setIntField(this, 11, readTags);
        return this;
    }

    /**
     * < Number of failed read tag commands
     */
    @Field(12)
    public int readErrors() {
        return this.io.getIntField(this, 12);
    }

    /**
     * < Number of failed read tag commands
     */
    @Field(12)
    public NUR_DIAG_REPORT readErrors(int readErrors) {
        this.io.setIntField(this, 12, readErrors);
        return this;
    }

    /**
     * < Number of successfully write tag commands
     */
    @Field(13)
    public int writeTags() {
        return this.io.getIntField(this, 13);
    }

    /**
     * < Number of successfully write tag commands
     */
    @Field(13)
    public NUR_DIAG_REPORT writeTags(int writeTags) {
        this.io.setIntField(this, 13, writeTags);
        return this;
    }

    /**
     * < Number of failed write tag commands
     */
    @Field(14)
    public int writeErrors() {
        return this.io.getIntField(this, 14);
    }

    /**
     * < Number of failed write tag commands
     */
    @Field(14)
    public NUR_DIAG_REPORT writeErrors(int writeErrors) {
        this.io.setIntField(this, 14, writeErrors);
        return this;
    }

    /**
     * < Number of temporary error conditions (over temp, low voltage) occured
     */
    @Field(15)
    public int errorConds() {
        return this.io.getIntField(this, 15);
    }

    /**
     * < Number of temporary error conditions (over temp, low voltage) occured
     */
    @Field(15)
    public NUR_DIAG_REPORT errorConds(int errorConds) {
        this.io.setIntField(this, 15, errorConds);
        return this;
    }

    /**
     * < Number of invalid setup errors
     */
    @Field(16)
    public int setupErrs() {
        return this.io.getIntField(this, 16);
    }

    /**
     * < Number of invalid setup errors
     */
    @Field(16)
    public NUR_DIAG_REPORT setupErrs(int setupErrs) {
        this.io.setIntField(this, 16, setupErrs);
        return this;
    }

    /**
     * < Number of invalid (not supported) commands received
     */
    @Field(17)
    public int invalidCmds() {
        return this.io.getIntField(this, 17);
    }

    /**
     * < Number of invalid (not supported) commands received
     */
    @Field(17)
    public NUR_DIAG_REPORT invalidCmds(int invalidCmds) {
        this.io.setIntField(this, 17, invalidCmds);
        return this;
    }
}
