package nurapi;

import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;

/**
 * Tag RSSI filter.
 * <br>
 *
 * @sa NurApiGetModuleSetup(), NurApiSetModuleSetup()<br>
 * <i>native declaration : nur_sdk-master\native\include\NurAPI.h:271</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("NurApi")
public class NUR_RSSI_FILTER extends StructObject {
    static {
        BridJ.register();
    }

    public NUR_RSSI_FILTER() {
        super();
    }

    public NUR_RSSI_FILTER(Pointer pointer) {
        super(pointer);
    }

    /**
     * < Minimum accepted RSSI in dBm. Use 0 to disable filtering.
     */
    @Field(0)
    public byte min() {
        return this.io.getByteField(this, 0);
    }

    /**
     * < Minimum accepted RSSI in dBm. Use 0 to disable filtering.
     */
    @Field(0)
    public NUR_RSSI_FILTER min(byte min) {
        this.io.setByteField(this, 0, min);
        return this;
    }

    /**
     * < Maximum accepted RSSI in dBm. Use 0 to disable filtering.
     */
    @Field(1)
    public byte max() {
        return this.io.getByteField(this, 1);
    }

    /**
     * < Maximum accepted RSSI in dBm. Use 0 to disable filtering.
     */
    @Field(1)
    public NUR_RSSI_FILTER max(byte max) {
        this.io.setByteField(this, 1, max);
        return this;
    }
}
