package nurapi;

import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;

/**
 * NUR_NOTIFICATION_TUNEEVENT data.<br>
 * <i>native declaration : nur_sdk-master\native\include\NurAPI.h:606</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("NurApi")
public class NUR_TUNEEVENT_DATA extends StructObject {
    static {
        BridJ.register();
    }

    public NUR_TUNEEVENT_DATA() {
        super();
    }

    public NUR_TUNEEVENT_DATA(Pointer pointer) {
        super(pointer);
    }

    /**
     * < Tuning capacitor 1 value
     */
    @Field(0)
    public byte cap1() {
        return this.io.getByteField(this, 0);
    }

    /**
     * < Tuning capacitor 1 value
     */
    @Field(0)
    public NUR_TUNEEVENT_DATA cap1(byte cap1) {
        this.io.setByteField(this, 0, cap1);
        return this;
    }

    /**
     * < Tuning capacitor 2 value
     */
    @Field(1)
    public byte cap2() {
        return this.io.getByteField(this, 1);
    }

    /**
     * < Tuning capacitor 2 value
     */
    @Field(1)
    public NUR_TUNEEVENT_DATA cap2(byte cap2) {
        this.io.setByteField(this, 1, cap2);
        return this;
    }

    /**
     * < Reflected power in dBm*1000
     */
    @Field(2)
    public int reflPower_dBm() {
        return this.io.getIntField(this, 2);
    }

    /**
     * < Reflected power in dBm*1000
     */
    @Field(2)
    public NUR_TUNEEVENT_DATA reflPower_dBm(int reflPower_dBm) {
        this.io.setIntField(this, 2, reflPower_dBm);
        return this;
    }

    /**
     * < Antenna ID
     */
    @Field(3)
    public byte antenna() {
        return this.io.getByteField(this, 3);
    }

    /**
     * < Antenna ID
     */
    @Field(3)
    public NUR_TUNEEVENT_DATA antenna(byte antenna) {
        this.io.setByteField(this, 3, antenna);
        return this;
    }

    /**
     * < Frequency in kHz
     */
    @Field(4)
    public int freqKhz() {
        return this.io.getIntField(this, 4);
    }

    /**
     * < Frequency in kHz
     */
    @Field(4)
    public NUR_TUNEEVENT_DATA freqKhz(int freqKhz) {
        this.io.setIntField(this, 4, freqKhz);
        return this;
    }
}
