package nurapi;

import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;

/**
 * Module sensor configuration.
 * <br>
 *
 * @sa NurApiSetSensorConfig(), NurApiGetSensorConfig(), NUR_GPIO_ACTION, NUR_NOTIFICATION_IOCHANGE, NUR_NOTIFICATION_TRIGGERREAD<br>
 * <i>native declaration : nur_sdk-master\native\include\NurAPI.h:235</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("NurApi")
public class NUR_SENSOR_CONFIG extends StructObject {
    static {
        BridJ.register();
    }

    public NUR_SENSOR_CONFIG() {
        super();
    }

    public NUR_SENSOR_CONFIG(Pointer pointer) {
        super(pointer);
    }

    /**
     * < TRUE if tap sensor is enabled.
     */
    @Field(0)
    public int tapEnabled() {
        return this.io.getIntField(this, 0);
    }

    /**
     * < TRUE if tap sensor is enabled.
     */
    @Field(0)
    public NUR_SENSOR_CONFIG tapEnabled(int tapEnabled) {
        this.io.setIntField(this, 0, tapEnabled);
        return this;
    }

    /**
     * < Action for tap sensor. GPIO_ACT_NOTIFY or GPIO_ACT_SCANTAG.
     */
    @Field(1)
    public int tapAction() {
        return this.io.getIntField(this, 1);
    }

    /**
     * < Action for tap sensor. GPIO_ACT_NOTIFY or GPIO_ACT_SCANTAG.
     */
    @Field(1)
    public NUR_SENSOR_CONFIG tapAction(int tapAction) {
        this.io.setIntField(this, 1, tapAction);
        return this;
    }

    /**
     * < TRUE if light sensor is enabled.
     */
    @Field(2)
    public int lightEnabled() {
        return this.io.getIntField(this, 2);
    }

    /**
     * < TRUE if light sensor is enabled.
     */
    @Field(2)
    public NUR_SENSOR_CONFIG lightEnabled(int lightEnabled) {
        this.io.setIntField(this, 2, lightEnabled);
        return this;
    }

    /**
     * < Action for light sensor. GPIO_ACT_NOTIFY or GPIO_ACT_SCANTAG.
     */
    @Field(3)
    public int lightAction() {
        return this.io.getIntField(this, 3);
    }

    /**
     * < Action for light sensor. GPIO_ACT_NOTIFY or GPIO_ACT_SCANTAG.
     */
    @Field(3)
    public NUR_SENSOR_CONFIG lightAction(int lightAction) {
        this.io.setIntField(this, 3, lightAction);
        return this;
    }
}
