package nurapi;

import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;

/**
 * Antenna mapping that maps logical antenna number to an antenna name.<br>
 * <i>native declaration : nur_sdk-master\native\include\NurAPI.h:611</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("NurApi")
public class NUR_ANTENNA_MAPPING extends StructObject {
    static {
        BridJ.register();
    }

    public NUR_ANTENNA_MAPPING() {
        super();
    }

    public NUR_ANTENNA_MAPPING(Pointer pointer) {
        super(pointer);
    }

    /**
     * < Logical number of the antenna.
     */
    @Field(0)
    public int antennaId() {
        return this.io.getIntField(this, 0);
    }

    /**
     * < Logical number of the antenna.
     */
    @Field(0)
    public NUR_ANTENNA_MAPPING antennaId(int antennaId) {
        this.io.setIntField(this, 0, antennaId);
        return this;
    }

    /**
     * < Name of the antenna + 0.<br>
     * C type : TCHAR[16 + 1]
     */
    @Array({16 + 1})
    @Field(1)
    public Pointer<Byte> name() {
        return this.io.getPointerField(this, 1);
    }
}
