package nurapi;

import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;

/**
 * Data sent within tag tracking change event.<br>
 * <i>native declaration : nur_sdk-master\native\include\NurAPI.h:50</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("NurApi")
public class NUR_TTCHANGED_DATA extends StructObject {
    static {
        BridJ.register();
    }

    public NUR_TTCHANGED_DATA() {
        super();
    }

    public NUR_TTCHANGED_DATA(Pointer pointer) {
        super(pointer);
    }

    @Field(0)
    public int readSource() {
        return this.io.getIntField(this, 0);
    }

    @Field(0)
    public NUR_TTCHANGED_DATA readSource(int readSource) {
        this.io.setIntField(this, 0, readSource);
        return this;
    }

    @Field(1)
    public int changedCount() {
        return this.io.getIntField(this, 1);
    }

    @Field(1)
    public NUR_TTCHANGED_DATA changedCount(int changedCount) {
        this.io.setIntField(this, 1, changedCount);
        return this;
    }

    @Field(2)
    public int changedEventMask() {
        return this.io.getIntField(this, 2);
    }

    @Field(2)
    public NUR_TTCHANGED_DATA changedEventMask(int changedEventMask) {
        this.io.setIntField(this, 2, changedEventMask);
        return this;
    }

    @Field(3)
    public int stopped() {
        return this.io.getIntField(this, 3);
    }

    @Field(3)
    public NUR_TTCHANGED_DATA stopped(int stopped) {
        this.io.setIntField(this, 3, stopped);
        return this;
    }
}
