package nurapi;

import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;

/**
 * Custom bit stream / exchange parameters.<br>
 * <i>native declaration : nur_sdk-master\native\include\NurAPI.h:404</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("NurApi")
public class NUR_CUSTEXCHANGE_PARAMS extends StructObject {
    static {
        BridJ.register();
    }

    public NUR_CUSTEXCHANGE_PARAMS() {
        super();
    }

    public NUR_CUSTEXCHANGE_PARAMS(Pointer pointer) {
        super(pointer);
    }

    @Field(0)
    public short txLen() {
        return this.io.getShortField(this, 0);
    }

    @Field(0)
    public NUR_CUSTEXCHANGE_PARAMS txLen(short txLen) {
        this.io.setShortField(this, 0, txLen);
        return this;
    }

    @Field(1)
    public short rxLen() {
        return this.io.getShortField(this, 1);
    }

    @Field(1)
    public NUR_CUSTEXCHANGE_PARAMS rxLen(short rxLen) {
        this.io.setShortField(this, 1, rxLen);
        return this;
    }

    @Field(2)
    public int timeout() {
        return this.io.getIntField(this, 2);
    }

    @Field(2)
    public NUR_CUSTEXCHANGE_PARAMS timeout(int timeout) {
        this.io.setIntField(this, 2, timeout);
        return this;
    }

    @Field(3)
    public int asWrite() {
        return this.io.getIntField(this, 3);
    }

    @Field(3)
    public NUR_CUSTEXCHANGE_PARAMS asWrite(int asWrite) {
        this.io.setIntField(this, 3, asWrite);
        return this;
    }

    @Field(4)
    public int appendHandle() {
        return this.io.getIntField(this, 4);
    }

    @Field(4)
    public NUR_CUSTEXCHANGE_PARAMS appendHandle(int appendHandle) {
        this.io.setIntField(this, 4, appendHandle);
        return this;
    }

    @Field(5)
    public int xorRN16() {
        return this.io.getIntField(this, 5);
    }

    @Field(5)
    public NUR_CUSTEXCHANGE_PARAMS xorRN16(int xorRN16) {
        this.io.setIntField(this, 5, xorRN16);
        return this;
    }

    @Field(6)
    public int txOnly() {
        return this.io.getIntField(this, 6);
    }

    @Field(6)
    public NUR_CUSTEXCHANGE_PARAMS txOnly(int txOnly) {
        this.io.setIntField(this, 6, txOnly);
        return this;
    }

    @Field(7)
    public int noTxCRC() {
        return this.io.getIntField(this, 7);
    }

    @Field(7)
    public NUR_CUSTEXCHANGE_PARAMS noTxCRC(int noTxCRC) {
        this.io.setIntField(this, 7, noTxCRC);
        return this;
    }

    @Field(8)
    public int noRxCRC() {
        return this.io.getIntField(this, 8);
    }

    @Field(8)
    public NUR_CUSTEXCHANGE_PARAMS noRxCRC(int noRxCRC) {
        this.io.setIntField(this, 8, noRxCRC);
        return this;
    }

    @Field(9)
    public int txCRC5() {
        return this.io.getIntField(this, 9);
    }

    @Field(9)
    public NUR_CUSTEXCHANGE_PARAMS txCRC5(int txCRC5) {
        this.io.setIntField(this, 9, txCRC5);
        return this;
    }

    @Field(10)
    public int rxLenUnknown() {
        return this.io.getIntField(this, 10);
    }

    @Field(10)
    public NUR_CUSTEXCHANGE_PARAMS rxLenUnknown(int rxLenUnknown) {
        this.io.setIntField(this, 10, rxLenUnknown);
        return this;
    }

    @Field(11)
    public int rxStripHandle() {
        return this.io.getIntField(this, 11);
    }

    @Field(11)
    public NUR_CUSTEXCHANGE_PARAMS rxStripHandle(int rxStripHandle) {
        this.io.setIntField(this, 11, rxStripHandle);
        return this;
    }

    /**
     * C type : BYTE[1024 / 8]
     */
    @Array({1024 / 8})
    @Field(12)
    public Pointer<Byte> bitBuffer() {
        return this.io.getPointerField(this, 12);
    }
}
