package nurapi;

import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;

/**
 * NUR_IMAGE_INFO holds information about NUR module's image file.
 * <br>
 *
 * @sa NurApiGetImageInfo, NUR_BINFILEFORMAT<br>
 * <i>native declaration : nur_sdk-master\native\include\NurAPI.h:204</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("NurApi")
public class NUR_IMAGE_INFO extends StructObject {
    static {
        BridJ.register();
    }

    public NUR_IMAGE_INFO() {
        super();
    }

    public NUR_IMAGE_INFO(Pointer pointer) {
        super(pointer);
    }

    /**
     * < TRUE if the contents of the file were guessed.
     */
    @Field(0)
    public int dwType() {
        return this.io.getIntField(this, 0);
    }

    /**
     * < TRUE if the contents of the file were guessed.
     */
    @Field(0)
    public NUR_IMAGE_INFO dwType(int dwType) {
        this.io.setIntField(this, 0, dwType);
        return this;
    }

    /**
     * < Application / bootloader<br>
     * C type : TCHAR[32]
     */
    @Array({32})
    @Field(1)
    public Pointer<Byte> desc() {
        return this.io.getPointerField(this, 1);
    }

    /**
     * < NUR05W, xNUR, NUR05WL2<br>
     * C type : TCHAR[32]
     */
    @Array({32})
    @Field(2)
    public Pointer<Byte> modArch() {
        return this.io.getPointerField(this, 2);
    }

    /**
     * < Actual size of the image.
     */
    @Field(3)
    public int binSize() {
        return this.io.getIntField(this, 3);
    }

    /**
     * < Actual size of the image.
     */
    @Field(3)
    public NUR_IMAGE_INFO binSize(int binSize) {
        this.io.setIntField(this, 3, binSize);
        return this;
    }
}
