package nurapi;

import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;

/**
 * Tag tracking routine function parameters
 * <br>
 *
 * @sa NurApiStartTagTracking()<br>
 * <i>native declaration : nur_sdk-master\native\include\NurAPI.h:21</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("NurApi")
public class NUR_TAGTRACKING_CONFIG extends StructObject {
    static {
        BridJ.register();
    }

    public NUR_TAGTRACKING_CONFIG() {
        super();
    }

    public NUR_TAGTRACKING_CONFIG(Pointer pointer) {
        super(pointer);
    }

    @Field(0)
    public int flags() {
        return this.io.getIntField(this, 0);
    }

    @Field(0)
    public NUR_TAGTRACKING_CONFIG flags(int flags) {
        this.io.setIntField(this, 0, flags);
        return this;
    }

    @Field(1)
    public int events() {
        return this.io.getIntField(this, 1);
    }

    @Field(1)
    public NUR_TAGTRACKING_CONFIG events(int events) {
        this.io.setIntField(this, 1, events);
        return this;
    }

    @Field(2)
    public int rssiDeltaFilter() {
        return this.io.getIntField(this, 2);
    }

    @Field(2)
    public NUR_TAGTRACKING_CONFIG rssiDeltaFilter(int rssiDeltaFilter) {
        this.io.setIntField(this, 2, rssiDeltaFilter);
        return this;
    }

    @Field(3)
    public float positionDeltaFilter() {
        return this.io.getFloatField(this, 3);
    }

    @Field(3)
    public NUR_TAGTRACKING_CONFIG positionDeltaFilter(float positionDeltaFilter) {
        this.io.setFloatField(this, 3, positionDeltaFilter);
        return this;
    }

    @Field(4)
    public int scanUntilNewTagsCount() {
        return this.io.getIntField(this, 4);
    }

    @Field(4)
    public NUR_TAGTRACKING_CONFIG scanUntilNewTagsCount(int scanUntilNewTagsCount) {
        this.io.setIntField(this, 4, scanUntilNewTagsCount);
        return this;
    }

    @Field(5)
    public int visibilityTimeout() {
        return this.io.getIntField(this, 5);
    }

    @Field(5)
    public NUR_TAGTRACKING_CONFIG visibilityTimeout(int visibilityTimeout) {
        this.io.setIntField(this, 5, visibilityTimeout);
        return this;
    }

    @Field(6)
    public byte selectBank() {
        return this.io.getByteField(this, 6);
    }

    @Field(6)
    public NUR_TAGTRACKING_CONFIG selectBank(byte selectBank) {
        this.io.setByteField(this, 6, selectBank);
        return this;
    }

    @Field(7)
    public int selectAddress() {
        return this.io.getIntField(this, 7);
    }

    @Field(7)
    public NUR_TAGTRACKING_CONFIG selectAddress(int selectAddress) {
        this.io.setIntField(this, 7, selectAddress);
        return this;
    }

    @Field(8)
    public short selectMaskBitLength() {
        return this.io.getShortField(this, 8);
    }

    @Field(8)
    public NUR_TAGTRACKING_CONFIG selectMaskBitLength(short selectMaskBitLength) {
        this.io.setShortField(this, 8, selectMaskBitLength);
        return this;
    }

    /**
     * C type : BYTE[(62)]
     */
    @Array({62})
    @Field(9)
    public Pointer<Byte> selectMask() {
        return this.io.getPointerField(this, 9);
    }

    @Field(10)
    public int inAntennaMask() {
        return this.io.getIntField(this, 10);
    }

    @Field(10)
    public NUR_TAGTRACKING_CONFIG inAntennaMask(int inAntennaMask) {
        this.io.setIntField(this, 10, inAntennaMask);
        return this;
    }

    @Field(11)
    public int outAntennaMask() {
        return this.io.getIntField(this, 11);
    }

    @Field(11)
    public NUR_TAGTRACKING_CONFIG outAntennaMask(int outAntennaMask) {
        this.io.setIntField(this, 11, outAntennaMask);
        return this;
    }

    @Field(12)
    public int complexFilterCnt() {
        return this.io.getIntField(this, 12);
    }

    @Field(12)
    public NUR_TAGTRACKING_CONFIG complexFilterCnt(int complexFilterCnt) {
        this.io.setIntField(this, 12, complexFilterCnt);
        return this;
    }

    /**
     * C type : NUR_INVEX_FILTER*
     */
    @Field(13)
    public Pointer<NUR_INVEX_FILTER> complexFilters() {
        return this.io.getPointerField(this, 13);
    }

    /**
     * C type : NUR_INVEX_FILTER*
     */
    @Field(13)
    public NUR_TAGTRACKING_CONFIG complexFilters(Pointer<NUR_INVEX_FILTER> complexFilters) {
        this.io.setPointerField(this, 13, complexFilters);
        return this;
    }

    /**
     * C type : NUR_INVEX_PARAMS*
     */
    @Field(14)
    public Pointer<NUR_INVEX_PARAMS> complexFilterParams() {
        return this.io.getPointerField(this, 14);
    }

    /**
     * C type : NUR_INVEX_PARAMS*
     */
    @Field(14)
    public NUR_TAGTRACKING_CONFIG complexFilterParams(Pointer<NUR_INVEX_PARAMS> complexFilterParams) {
        this.io.setPointerField(this, 14, complexFilterParams);
        return this;
    }
}
