package nurapi;

import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;

/**
 * Data sent with notification NUR_NOTIFICATION_PRGPRGRESS.
 * <br>
 *
 * @sa NurApiSetNotificationCallback(), NUR_NOTIFICATION_PRGPRGRESS, enum NUR_NOTIFICATION<br>
 * <i>native declaration : nur_sdk-master\native\include\NurAPI.h:76</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("NurApi")
public class NUR_PRGPROGRESS_DATA extends StructObject {
    static {
        BridJ.register();
    }

    public NUR_PRGPROGRESS_DATA() {
        super();
    }

    public NUR_PRGPROGRESS_DATA(Pointer pointer) {
        super(pointer);
    }

    /**
     * < Error code returned from page programming.
     */
    @Field(0)
    public int error() {
        return this.io.getIntField(this, 0);
    }

    /**
     * < Error code returned from page programming.
     */
    @Field(0)
    public NUR_PRGPROGRESS_DATA error(int error) {
        this.io.setIntField(this, 0, error);
        return this;
    }

    /**
     * < Current page, this is -1 in first notification before programming started.
     */
    @Field(1)
    public int curPage() {
        return this.io.getIntField(this, 1);
    }

    /**
     * < Current page, this is -1 in first notification before programming started.
     */
    @Field(1)
    public NUR_PRGPROGRESS_DATA curPage(int curPage) {
        this.io.setIntField(this, 1, curPage);
        return this;
    }

    /**
     * < Total number of pages to program.
     */
    @Field(2)
    public int totalPages() {
        return this.io.getIntField(this, 2);
    }

    /**
     * < Total number of pages to program.
     */
    @Field(2)
    public NUR_PRGPROGRESS_DATA totalPages(int totalPages) {
        this.io.setIntField(this, 2, totalPages);
        return this;
    }
}
