package nurapi;

import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;

/**
 * NUR_INVENTORY_RESPONSE holds last inventory result.
 * <br>
 *
 * @sa NurApiInventory(), NurApiInventorySelect32(), NurApiInventorySelectByEPC()<br>
 * <i>native declaration : nur_sdk-master\native\include\NurAPI.h:152</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("NurApi")
public class NUR_INVENTORY_RESPONSE extends StructObject {
    static {
        BridJ.register();
    }

    public NUR_INVENTORY_RESPONSE() {
        super();
    }

    public NUR_INVENTORY_RESPONSE(Pointer pointer) {
        super(pointer);
    }

    /**
     * < Number of tags found in this inventory.
     */
    @Field(0)
    public int numTagsFound() {
        return this.io.getIntField(this, 0);
    }

    /**
     * < Number of tags found in this inventory.
     */
    @Field(0)
    public NUR_INVENTORY_RESPONSE numTagsFound(int numTagsFound) {
        this.io.setIntField(this, 0, numTagsFound);
        return this;
    }

    /**
     * < Total number of tags in module memory.
     */
    @Field(1)
    public int numTagsMem() {
        return this.io.getIntField(this, 1);
    }

    /**
     * < Total number of tags in module memory.
     */
    @Field(1)
    public NUR_INVENTORY_RESPONSE numTagsMem(int numTagsMem) {
        this.io.setIntField(this, 1, numTagsMem);
        return this;
    }

    /**
     * < Number of full Q rounds done in this inventory.
     */
    @Field(2)
    public int roundsDone() {
        return this.io.getIntField(this, 2);
    }

    /**
     * < Number of full Q rounds done in this inventory.
     */
    @Field(2)
    public NUR_INVENTORY_RESPONSE roundsDone(int roundsDone) {
        this.io.setIntField(this, 2, roundsDone);
        return this;
    }

    /**
     * < Number of possible collisions or reception errors in this inventory.
     */
    @Field(3)
    public int collisions() {
        return this.io.getIntField(this, 3);
    }

    /**
     * < Number of possible collisions or reception errors in this inventory.
     */
    @Field(3)
    public NUR_INVENTORY_RESPONSE collisions(int collisions) {
        this.io.setIntField(this, 3, collisions);
        return this;
    }

    /**
     * < Q used in this inventory.
     */
    @Field(4)
    public int Q() {
        return this.io.getIntField(this, 4);
    }

    /**
     * < Q used in this inventory.
     */
    @Field(4)
    public NUR_INVENTORY_RESPONSE Q(int Q) {
        this.io.setIntField(this, 4, Q);
        return this;
    }
}
