package nurapi;

import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;

/**
 * Single GPIO status.
 * <br>
 *
 * @sa NurApiGetGPIOStatus(), enum NUR_GPIO_TYPE<br>
 * <i>native declaration : nur_sdk-master\native\include\NurAPI.h:263</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("NurApi")
public class NUR_GPIO_STATUS extends StructObject {
    static {
        BridJ.register();
    }

    public NUR_GPIO_STATUS() {
        super();
    }

    public NUR_GPIO_STATUS(Pointer pointer) {
        super(pointer);
    }

    /**
     * < TRUE if GPIO is enabled.
     */
    @Field(0)
    public int enabled() {
        return this.io.getIntField(this, 0);
    }

    /**
     * < TRUE if GPIO is enabled.
     */
    @Field(0)
    public NUR_GPIO_STATUS enabled(int enabled) {
        this.io.setIntField(this, 0, enabled);
        return this;
    }

    /**
     * < Type of the GPIO. see enum NUR_GPIO_TYPE
     */
    @Field(1)
    public int type() {
        return this.io.getIntField(this, 1);
    }

    /**
     * < Type of the GPIO. see enum NUR_GPIO_TYPE
     */
    @Field(1)
    public NUR_GPIO_STATUS type(int type) {
        this.io.setIntField(this, 1, type);
        return this;
    }

    /**
     * < State of the GPIO. Only valid if GPIO is configured as input (NUR_GPIO_TYPE_INPUT).
     */
    @Field(2)
    public int state() {
        return this.io.getIntField(this, 2);
    }

    /**
     * < State of the GPIO. Only valid if GPIO is configured as input (NUR_GPIO_TYPE_INPUT).
     */
    @Field(2)
    public NUR_GPIO_STATUS state(int state) {
        this.io.setIntField(this, 2, state);
        return this;
    }
}
