package nurapi;

import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;

/**
 * Contains WLAN connection profile information.
 * <br>
 *
 * @sa NurApiWlanGetProfile, NurApiWlanSetProfile, NurApiWlanDeleteProfile<br>
 * <i>native declaration : nur_sdk-master\native\include\NurAPI.h:654</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("NurApi")
public class NUR_WLANPROFILE extends StructObject {
    static {
        BridJ.register();
    }

    public NUR_WLANPROFILE() {
        super();
    }

    public NUR_WLANPROFILE(Pointer pointer) {
        super(pointer);
    }

    /**
     * < Index of profile (1-7)
     */
    @Field(0)
    public int index() {
        return this.io.getIntField(this, 0);
    }

    /**
     * < Index of profile (1-7)
     */
    @Field(0)
    public NUR_WLANPROFILE index(int index) {
        this.io.setIntField(this, 0, index);
        return this;
    }

    /**
     * < SSID of target AP<br>
     * C type : BYTE[32]
     */
    @Array({32})
    @Field(1)
    public Pointer<Byte> ssid() {
        return this.io.getPointerField(this, 1);
    }

    /**
     * < MAC of target AP<br>
     * C type : BYTE[6]
     */
    @Array({6})
    @Field(2)
    public Pointer<Byte> mac() {
        return this.io.getPointerField(this, 2);
    }

    /**
     * < Security type: Open,WEP WPA1, WPA2
     */
    @Field(3)
    public byte secType() {
        return this.io.getByteField(this, 3);
    }

    /**
     * < Security type: Open,WEP WPA1, WPA2
     */
    @Field(3)
    public NUR_WLANPROFILE secType(byte secType) {
        this.io.setByteField(this, 3, secType);
        return this;
    }

    /**
     * < Security key:<br>
     * C type : BYTE[32]
     */
    @Array({32})
    @Field(4)
    public Pointer<Byte> secKey() {
        return this.io.getPointerField(this, 4);
    }

    /**
     * < ExtUser<br>
     * C type : BYTE[32]
     */
    @Array({32})
    @Field(5)
    public Pointer<Byte> extUser() {
        return this.io.getPointerField(this, 5);
    }

    /**
     * < AnonUser<br>
     * C type : BYTE[32]
     */
    @Array({32})
    @Field(6)
    public Pointer<Byte> anonUser() {
        return this.io.getPointerField(this, 6);
    }

    /**
     * < certIndex
     */
    @Field(7)
    public byte certIndex() {
        return this.io.getByteField(this, 7);
    }

    /**
     * < certIndex
     */
    @Field(7)
    public NUR_WLANPROFILE certIndex(byte certIndex) {
        this.io.setByteField(this, 7, certIndex);
        return this;
    }

    /**
     * < EAP Method
     */
    @Field(8)
    public int eapMethod() {
        return this.io.getIntField(this, 8);
    }

    /**
     * < EAP Method
     */
    @Field(8)
    public NUR_WLANPROFILE eapMethod(int eapMethod) {
        this.io.setIntField(this, 8, eapMethod);
        return this;
    }

    /**
     * < Priority. Priority. 0-7 (0=Highest)
     */
    @Field(9)
    public int priority() {
        return this.io.getIntField(this, 9);
    }

    /**
     * < Priority. Priority. 0-7 (0=Highest)
     */
    @Field(9)
    public NUR_WLANPROFILE priority(int priority) {
        this.io.setIntField(this, 9, priority);
        return this;
    }
}
