package nurapi;

import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.CLong;
import org.bridj.ann.Field;
import org.bridj.ann.Library;

/**
 * Contains WLAn module's general information and current status.
 * <br>
 *
 * @sa NurApiWlanGetStatus<br>
 * <i>native declaration : nur_sdk-master\native\include\NurAPI.h:638</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("NurApi")
public class NUR_WLANSTATUS extends StructObject {
    static {
        BridJ.register();
    }

    public NUR_WLANSTATUS() {
        super();
    }

    public NUR_WLANSTATUS(Pointer pointer) {
        super(pointer);
    }

    /**
     * < WLan status 0=disable 1=enable 2=initializing.
     */
    @Field(0)
    public int wlan_status() {
        return this.io.getIntField(this, 0);
    }

    /**
     * < WLan status 0=disable 1=enable 2=initializing.
     */
    @Field(0)
    public NUR_WLANSTATUS wlan_status(int wlan_status) {
        this.io.setIntField(this, 0, wlan_status);
        return this;
    }

    @CLong
    @Field(1)
    public long role() {
        return this.io.getCLongField(this, 1);
    }

    @CLong
    @Field(1)
    public NUR_WLANSTATUS role(long role) {
        this.io.setCLongField(this, 1, role);
        return this;
    }

    /**
     * < see enum WLAN_STATUS
     */
    @Field(2)
    public int wlan_connection_status() {
        return this.io.getIntField(this, 2);
    }

    /**
     * < see enum WLAN_STATUS
     */
    @Field(2)
    public NUR_WLANSTATUS wlan_connection_status(int wlan_connection_status) {
        this.io.setIntField(this, 2, wlan_connection_status);
        return this;
    }

    /**
     * < Profile count.
     */
    @Field(3)
    public int profile_count() {
        return this.io.getIntField(this, 3);
    }

    /**
     * < Profile count.
     */
    @Field(3)
    public NUR_WLANSTATUS profile_count(int profile_count) {
        this.io.setIntField(this, 3, profile_count);
        return this;
    }

    /**
     * < last error code
     */
    @CLong
    @Field(4)
    public long lasterror() {
        return this.io.getCLongField(this, 4);
    }

    /**
     * < last error code
     */
    @CLong
    @Field(4)
    public NUR_WLANSTATUS lasterror(long lasterror) {
        this.io.setCLongField(this, 4, lasterror);
        return this;
    }

    /**
     * < Chip ID
     */
    @Field(5)
    public int ChipId() {
        return this.io.getIntField(this, 5);
    }

    /**
     * < Chip ID
     */
    @Field(5)
    public NUR_WLANSTATUS ChipId(int ChipId) {
        this.io.setIntField(this, 5, ChipId);
        return this;
    }

    /**
     * < FW Version<br>
     * C type : BYTE[16]
     */
    @Array({16})
    @Field(6)
    public Pointer<Byte> FwVersion() {
        return this.io.getPointerField(this, 6);
    }

    /**
     * < PHY Version<br>
     * C type : BYTE[16]
     */
    @Array({16})
    @Field(7)
    public Pointer<Byte> PhyVersion() {
        return this.io.getPointerField(this, 7);
    }

    /**
     * < NWP Version<br>
     * C type : BYTE[16]
     */
    @Array({16})
    @Field(8)
    public Pointer<Byte> NwpVersion() {
        return this.io.getPointerField(this, 8);
    }

    /**
     * < Host driver Version<br>
     * C type : BYTE[16]
     */
    @Array({16})
    @Field(9)
    public Pointer<Byte> HostDrvVer() {
        return this.io.getPointerField(this, 9);
    }

    /**
     * < ROM Version
     */
    @Field(10)
    public int RomVersion() {
        return this.io.getIntField(this, 10);
    }

    /**
     * < ROM Version
     */
    @Field(10)
    public NUR_WLANSTATUS RomVersion(int RomVersion) {
        this.io.setIntField(this, 10, RomVersion);
        return this;
    }

    /**
     * < IP
     */
    @Field(11)
    public int ip() {
        return this.io.getIntField(this, 11);
    }

    /**
     * < IP
     */
    @Field(11)
    public NUR_WLANSTATUS ip(int ip) {
        this.io.setIntField(this, 11, ip);
        return this;
    }

    /**
     * < GW IP
     */
    @Field(12)
    public int gwip() {
        return this.io.getIntField(this, 12);
    }

    /**
     * < GW IP
     */
    @Field(12)
    public NUR_WLANSTATUS gwip(int gwip) {
        this.io.setIntField(this, 12, gwip);
        return this;
    }

    /**
     * < MAC address.<br>
     * C type : BYTE[6]
     */
    @Array({6})
    @Field(13)
    public Pointer<Byte> mac() {
        return this.io.getPointerField(this, 13);
    }

    /**
     * < SSID.<br>
     * C type : BYTE[32]
     */
    @Array({32})
    @Field(14)
    public Pointer<Byte> ssid() {
        return this.io.getPointerField(this, 14);
    }

    /**
     * < SSID where connected to.<br>
     * C type : BYTE[32]
     */
    @Array({32})
    @Field(15)
    public Pointer<Byte> connection_ssid() {
        return this.io.getPointerField(this, 15);
    }

    /**
     * < MAC address where connected to.<br>
     * C type : BYTE[6]
     */
    @Array({6})
    @Field(16)
    public Pointer<Byte> connection_mac() {
        return this.io.getPointerField(this, 16);
    }

    /**
     * < Time in milliseconds how long network scan enabled
     */
    @CLong
    @Field(17)
    public long scantime() {
        return this.io.getCLongField(this, 17);
    }

    /**
     * < Time in milliseconds how long network scan enabled
     */
    @CLong
    @Field(17)
    public NUR_WLANSTATUS scantime(long scantime) {
        this.io.setCLongField(this, 17, scantime);
        return this;
    }

    /**
     * < Holds the average management frames RSSI as dBm
     */
    @Field(18)
    public short rssi_mgmnt() {
        return this.io.getShortField(this, 18);
    }

    /**
     * < Holds the average management frames RSSI as dBm
     */
    @Field(18)
    public NUR_WLANSTATUS rssi_mgmnt(short rssi_mgmnt) {
        this.io.setShortField(this, 18, rssi_mgmnt);
        return this;
    }

    /**
     * < Holds the average data + ctrl frames RSSI as dBm
     */
    @Field(19)
    public short rssi_datactrl() {
        return this.io.getShortField(this, 19);
    }

    /**
     * < Holds the average data + ctrl frames RSSI as dBm
     */
    @Field(19)
    public NUR_WLANSTATUS rssi_datactrl(short rssi_datactrl) {
        this.io.setShortField(this, 19, rssi_datactrl);
        return this;
    }

    /**
     * < Reserved<br>
     * C type : BYTE[10]
     */
    @Array({10})
    @Field(20)
    public Pointer<Byte> reserved() {
        return this.io.getPointerField(this, 20);
    }
}
